"""
Scenario loader and knowledge retrieval.

Parses any scenario markdown file into three layers:

  character_text  — who the client IS: identity, personality, team, limitations.
                    Always in the system prompt. Contains NO factual data points.

  surface_items   — facts the client would share if asked about the relevant topic.
                    Gated: unlocked when the question is about that topic area.
                    Parsed from: What the Client Can Articulate (legacy) or
                    Discovery Items (generated format).

  tacit_items     — facts the client knows but guards carefully.
                    Gated: unlocked only when asked specifically about the
                    current state or process for that topic.
                    Parsed from: What the Client Knows But Won't Volunteer (legacy).

Surface and tacit items are injected into the system prompt only after the consultant
earns them. The LLM cannot reveal what it cannot see. The number of items returned per
turn is an output of the relevance judgment — proportional to what the question earned.

Two file formats are supported:

  LEGACY (single-persona, ## sections throughout):
    CHARACTER sections → character_text:
      Identity, Maturity Level, Team Members, Personality and Communication Style,
      Company Overview, Character Knowledge
    SURFACE sections → surface_items:
      What the Client Can Articulate, Discovery Items
    TACIT section → tacit_items:
      What the Client Knows But Won't Volunteer [Tacit Knowledge]
    METADATA sections (extracted, not sent to client LLM):
      Consultant Briefing → scenario.briefing
      Topics → scenario.topic_taxonomy
    DROPPED sections:
      Scope Note, Scenario Parameters, Technical Reference

  MULTI-PERSONA (## Persona: {name} blocks, generated by phase6_assemble.py):
    Shared sections (before the first ## Persona: header):
      Topics → scenario.topic_taxonomy
      Consultant Briefing → scenario.briefing
      Scenario Parameters → dropped
    Per-persona sections (### sub-headers inside ## Persona: {name}):
      ### Identity, Persona Maturity, Personality and Communication Style,
          Character Knowledge, Team Members → character_text
      ### Discovery Items → surface_items
        Item IDs are the explicit [DI-XX] identifiers from the bullet format.
      ### What the Client Knows But Won't Volunteer → tacit_items (if present)

    load_scenario(path, persona="Danny") loads the Danny block.
    load_scenario(path) with no persona argument loads the first persona in the file.
"""

import re
import json
from dataclasses import dataclass, field
from pathlib import Path
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage as LCHumanMessage


@dataclass
class ScenarioItem:
    id: str      # slug derived from content
    content: str # the fact — injected into system prompt when unlocked
    layer: str   # "surface" or "tacit" — controls unlock threshold
    topic: str = ""  # subtopic code e.g. "iam/provisioning", empty if untagged


@dataclass
class Scenario:
    title: str
    character_text: str                        # always in system prompt
    briefing: str = ""                         # consultant-facing briefing text
    maturity: str = ""                         # raw maturity level section body — passed to evaluator
    topic_taxonomy: dict = field(default_factory=dict)  # code -> display name
    surface_items: list[ScenarioItem] = field(default_factory=list)
    tacit_items: list[ScenarioItem] = field(default_factory=list)


# Which section headers belong to character_text (case-insensitive partial match).
_CHARACTER_SECTIONS = [
    "identity",
    "maturity level",
    "team members",
    "personality and communication style",
    "company overview",       # always visible context — client knows this freely as manager
    "character knowledge",    # generated scenario format: rich narrative from Phase 4
]

# Which section headers to drop entirely (meta/training context).
_DROPPED_SECTIONS = [
    "scope note",
    "what the client genuinely doesn't know",
    "technical reference",
    "scenario parameters",    # generated scenario metadata — not sent to client LLM
]

# Consultant-facing sections — captured separately, not sent to client LLM.
_BRIEFING_SECTIONS = ["consultant briefing"]
_TAXONOMY_SECTIONS = ["topics"]


def _slugify(text: str, max_words: int = 5) -> str:
    words = re.sub(r"[^a-z0-9\s]", "", text.lower()).split()
    return "_".join(words[:max_words])


def _parse_bullets(section_body: str) -> list[tuple[str, str]]:
    """
    Return (content, topic) pairs for each bullet in a section body.
    Strips inline [topic: X] and any legacy [TIER N] markers from content.
    """
    results = []
    for match in re.finditer(r"^\s*-\s+(.+)$", section_body, re.MULTILINE):
        raw = match.group(1).strip()
        topic_match = re.search(r"\[topic:\s*([^\]]+)\]", raw)
        topic = topic_match.group(1).strip() if topic_match else ""
        content = re.sub(r"\s*\[[^\]]*\]", "", raw).strip().strip('"')
        if content:
            results.append((content, topic))
    return results


def _parse_discovery_item(line: str) -> tuple[str, str, str] | None:
    """
    Parse a generated-format discovery item bullet.

    Format: - [DI-01] [topic: iam/rbac] The content text here.

    Returns (item_id, content, topic) or None if the line does not match.
    The item_id is the explicit identifier (e.g. "DI-01") — not a slug.
    """
    match = re.match(r"^\s*-\s+\[([^\]]+)\]\s+(.*)", line)
    if not match:
        return None
    item_id = match.group(1).strip()
    rest = match.group(2).strip()
    topic_match = re.search(r"\[topic:\s*([^\]]+)\]", rest)
    topic = topic_match.group(1).strip() if topic_match else ""
    content = re.sub(r"\s*\[[^\]]*\]", "", rest).strip().strip('"')
    if not content:
        return None
    return item_id, content, topic


def _parse_taxonomy_body(body: str) -> dict[str, str]:
    """Parse a Topics section body into a {code: display_name} dict."""
    taxonomy = {}
    for line in body.splitlines():
        line = line.strip()
        if line and ":" in line:
            code, _, display = line.partition(":")
            taxonomy[code.strip()] = display.strip()
    return taxonomy


def load_scenario(path: str | Path, persona: str | None = None) -> Scenario:
    """
    Parse a scenario markdown file into a Scenario object.

    Supports two file formats:

    Legacy (single-persona, all ## sections):
        Loads character_text, surface_items, tacit_items, briefing, and
        topic_taxonomy from flat ## sections. persona argument is ignored.

    Multi-persona (## Persona: {name} blocks):
        Shared sections (Topics, Consultant Briefing) are loaded for all personas.
        If persona is specified, that persona's ## Persona: {name} block is loaded.
        If persona is None, the first persona block in the file is loaded.
        Discovery Items are parsed using explicit [DI-XX] IDs from bullet format.

    Args:
        path: Path to the scenario markdown file.
        persona: Name of the persona to load (multi-persona format only).
                 Case-insensitive. If None, loads the first persona.

    Raises:
        ValueError: If persona is specified but not found in the file.
    """
    text = Path(path).read_text()

    if re.search(r"^## Persona:", text, re.MULTILINE):
        return _load_multi_persona(text, Path(path), persona)
    return _load_legacy(text, Path(path))


def _load_legacy(text: str, path: Path) -> Scenario:
    """
    Load a single-persona (legacy) scenario file.

    All sections are at ## level. Character sections go into character_text;
    bullet sections become surface or tacit items; briefing and taxonomy are
    extracted separately.
    """
    title_match = re.search(r"#\s+Scenario:\s*(.+)", text)
    title = title_match.group(1).strip() if title_match else path.stem

    section_pattern = re.compile(r"(##[^\n]+)\n(.*?)(?=\n##|\Z)", re.DOTALL)
    sections = section_pattern.findall(text)

    character_parts: list[str] = []
    briefing_parts: list[str] = []
    maturity_text: str = ""
    topic_taxonomy: dict[str, str] = {}
    surface_items: list[ScenarioItem] = []
    tacit_items: list[ScenarioItem] = []
    seen_ids: dict[str, int] = {}

    def make_id(content: str) -> str:
        base = _slugify(content)
        count = seen_ids.get(base, 0)
        seen_ids[base] = count + 1
        return base if count == 0 else f"{base}_{count}"

    for header, body in sections:
        header_lower = header.lower()

        is_character = any(k in header_lower for k in _CHARACTER_SECTIONS)
        is_dropped = any(k in header_lower for k in _DROPPED_SECTIONS)
        is_briefing = any(k in header_lower for k in _BRIEFING_SECTIONS)
        is_taxonomy = any(k in header_lower for k in _TAXONOMY_SECTIONS)
        is_tacit = "tacit knowledge" in header_lower

        if is_dropped:
            continue

        if is_briefing:
            briefing_parts.append(body.strip())
            continue

        if is_taxonomy:
            topic_taxonomy.update(_parse_taxonomy_body(body))
            continue

        if is_character:
            character_parts.append(header.strip() + "\n" + body.strip())
            if "maturity level" in header_lower:
                maturity_text = body.strip()
            continue

        if is_tacit:
            for content, topic in _parse_bullets(body):
                tacit_items.append(ScenarioItem(
                    id=make_id(content),
                    content=content,
                    layer="tacit",
                    topic=topic,
                ))
            continue

        # Surface section — parse bullets.
        for content, topic in _parse_bullets(body):
            surface_items.append(ScenarioItem(
                id=make_id(content),
                content=content,
                layer="surface",
                topic=topic,
            ))

    return Scenario(
        title=title,
        character_text="\n\n".join(character_parts),
        briefing="\n".join(briefing_parts),
        maturity=maturity_text,
        topic_taxonomy=topic_taxonomy,
        surface_items=surface_items,
        tacit_items=tacit_items,
    )


def _load_multi_persona(text: str, path: Path, persona: str | None) -> Scenario:
    """
    Load a multi-persona scenario file.

    Shared sections (before the first ## Persona: header) supply the topic
    taxonomy and consultant briefing. The requested persona's ## Persona: {name}
    block supplies character_text and surface_items from its ### subsections.

    If persona is None, the first persona block in the file is used.
    """
    title_match = re.search(r"#\s+Scenario:\s*(.+)", text)
    title = title_match.group(1).strip() if title_match else path.stem

    # Locate where persona blocks begin.
    first_persona_pos = re.search(r"^## Persona:", text, re.MULTILINE).start()
    shared_text = text[:first_persona_pos]
    personas_text = text[first_persona_pos:]

    # --- Parse shared sections ---
    topic_taxonomy: dict[str, str] = {}
    briefing_parts: list[str] = []

    shared_section_pattern = re.compile(r"(##[^\n]+)\n(.*?)(?=\n##|\Z)", re.DOTALL)
    for header, body in shared_section_pattern.findall(shared_text):
        header_lower = header.lower()
        if any(k in header_lower for k in _DROPPED_SECTIONS):
            continue
        if any(k in header_lower for k in _BRIEFING_SECTIONS):
            briefing_parts.append(body.strip())
        elif any(k in header_lower for k in _TAXONOMY_SECTIONS):
            topic_taxonomy.update(_parse_taxonomy_body(body))

    # --- Find and extract persona blocks ---
    # Pattern: ## Persona: {name}\n{body} up to next ## Persona: or end of file.
    persona_block_pattern = re.compile(
        r"^## Persona:\s*(.+?)\n(.*?)(?=^## Persona:|\Z)",
        re.DOTALL | re.MULTILINE,
    )
    blocks = [(m.group(1).strip(), m.group(2)) for m in persona_block_pattern.finditer(personas_text)]

    if not blocks:
        raise ValueError(f"No ## Persona: sections found in {path}")

    if persona is None:
        chosen_name, persona_body = blocks[0]
    else:
        match = next(((name, body) for name, body in blocks if name.lower() == persona.lower()), None)
        if match is None:
            available = [name for name, _ in blocks]
            raise ValueError(
                f"Persona '{persona}' not found in {path}. "
                f"Available personas: {available}"
            )
        chosen_name, persona_body = match

    # --- Parse persona subsections (### headers) ---
    character_parts: list[str] = []
    surface_items: list[ScenarioItem] = []
    tacit_items: list[ScenarioItem] = []
    maturity_text: str = ""
    seen_ids: dict[str, int] = {}

    def make_id(id_hint: str) -> str:
        count = seen_ids.get(id_hint, 0)
        seen_ids[id_hint] = count + 1
        return id_hint if count == 0 else f"{id_hint}_{count}"

    subsection_pattern = re.compile(r"(###[^\n]+)\n(.*?)(?=\n###|\Z)", re.DOTALL)
    for header, body in subsection_pattern.findall(persona_body):
        header_lower = header.lower().lstrip("#").strip()
        is_discovery = "discovery items" in header_lower
        is_tacit = "tacit knowledge" in header_lower
        is_maturity = "maturity" in header_lower  # matches "persona maturity" and "maturity level"

        if is_discovery:
            # Parse [DI-XX] [topic: X] content bullets with explicit IDs.
            for line in body.splitlines():
                parsed = _parse_discovery_item(line)
                if parsed:
                    item_id, content, topic = parsed
                    surface_items.append(ScenarioItem(
                        id=make_id(item_id),
                        content=content,
                        layer="surface",
                        topic=topic,
                    ))
        elif is_tacit:
            for content, topic in _parse_bullets(body):
                slug = _slugify(content)
                tacit_items.append(ScenarioItem(
                    id=make_id(slug),
                    content=content,
                    layer="tacit",
                    topic=topic,
                ))
        else:
            # Identity, Persona Maturity, Personality, Character Knowledge,
            # Team Members — all go into character_text.
            # Normalize ### to ## so the heading level is consistent in the prompt.
            normalized_header = "##" + header.lstrip("#")
            character_parts.append(normalized_header.strip() + "\n" + body.strip())
            if is_maturity:
                maturity_text = body.strip()

    return Scenario(
        title=f"{title} — {chosen_name}",
        character_text="\n\n".join(character_parts),
        briefing="\n".join(briefing_parts),
        maturity=maturity_text,
        topic_taxonomy=topic_taxonomy,
        surface_items=surface_items,
        tacit_items=tacit_items,
    )


# ---------------------------------------------------------------------------
# Retrieval
# ---------------------------------------------------------------------------

_RETRIEVAL_PROMPT = """A consultant is interviewing a client about their current setup and situation.

Recent conversation (for context):
{recent_context}

The consultant's latest input: "{question}"

## YOUR TASK

First decide if this is a genuine question. Then, only if it is, find matching items.

### Step 1: Structural check (do this first)
Does the input contain at least one verb or explicit question word?
Question words: what, how, who, where, when, why, which, is, are, was, were,
do, does, did, can, could, will, would, should, have, has, had.

If NO verb or question word is present → the input is a bare noun phrase or topic name.
Set "is_genuine": false immediately. Do not proceed to step 2.

Examples that fail the structural check (no verb, no question word):
"object ownership?", "SCIM?", "clusters?", "self service?", "hub and spoke"

### Step 2: Intent check (only if step 1 passes)
Does the question ask specifically about THIS client's situation in a way that requires
knowing their particular reality? Use the conversation context to resolve references.

It is NOT genuine if:
- "what about X?" or "how about X?" — naming a topic is not asking about it
- It is a reaction or statement: "okay", "really?", "that's interesting"
- It is a catch-all: "anything else?", "tell me more", "share more"
- It asks how a technology works in general, not about this client specifically

### Step 3: Relevance matching (only if steps 1 and 2 pass)
For each candidate item, ask: does this question SPECIFICALLY ask about what THIS item
describes? Or is the item merely about the same general topic area as the question?

**Direct match — return the item:** The question specifically targets what this item
describes. The question could not be meaningfully answered without this item.
Ask yourself: if this item did not exist, would the question go unanswered?
If yes, it is a direct match.

**Topical association — do NOT return the item:** The item is about the same general
area as the question, but the question doesn't specifically address this item's content.
A question about a broad topic area is NOT a direct match for every item in that area.
Only the item (if any) that most centrally answers the question qualifies.

If the question is broad, return at most the one item that most centrally characterises
that area — or none if even that is a stretch. Broad questions earn little.
If the question is specific and directly targets something, return the items it targets.

Order matched_ids by decreasing relevance — most directly targeted item first.

SURFACE items:
{surface_items}

TACIT items:
{tacit_items}

### Output format
Output ONLY a JSON object. No reasoning, no explanation, no other text.
If "is_genuine" is false, "matched_ids" MUST be [].
matched_ids must be ordered: most directly targeted item first.

{{"is_genuine": true/false, "matched_ids": ["id", ...] or []}}
"""


def retrieve_relevant_knowledge(
    question: str,
    surface_items: list[ScenarioItem],
    tacit_items: list[ScenarioItem],
    already_revealed_ids: list[str],
    recent_context: str = "",
) -> list[ScenarioItem]:
    """
    Decide which knowledge items (if any) the consultant's question has earned.

    The retrieval LLM (Claude Sonnet 4.6) applies a three-step filter:
    1. Structural check — does the input contain a verb or question word?
       Bare noun phrases like "SCIM?" or "clusters?" fail immediately.
    2. Intent check — does it ask about this specific client's situation?
       Generic technology questions or catch-alls ("tell me more") are rejected.
    3. Relevance matching — for each candidate item, the test is:
       "if this item did not exist, would the question go unanswered?"
       This is direct specificity, not topical association. A broad question
       about "access management" does NOT earn every item about access — at most
       the one item that most centrally characterises that area.

    Tacit items have an extra pre-filter: a tacit item only becomes a candidate
    once a surface item in the same subtopic has already been revealed. This
    models how a client's guarded knowledge surfaces: first they describe the
    situation, then specific probing reveals the underlying problem.

    The [:3] cap at the end is a guardrail against prompt misjudgement — the
    prompt does the calibration work; the cap is a last resort. If it binds
    regularly, the prompt needs tuning, not the cap.

    Returns a list of newly unlocked ScenarioItem objects, ordered by relevance
    (most directly targeted item first), or an empty list if the question is
    not genuine or earns nothing.
    """
    unrevealed_surface = [t for t in surface_items if t.id not in already_revealed_ids]
    unrevealed_tacit = [t for t in tacit_items if t.id not in already_revealed_ids]

    # Tacit items only become candidates once a surface item in the same subtopic
    # has already been revealed. The LLM can't match what it can't see.
    revealed_subtopics = {
        t.topic for t in surface_items
        if t.id in already_revealed_ids and t.topic
    }
    eligible_tacit = [t for t in unrevealed_tacit if t.topic in revealed_subtopics]

    if not unrevealed_surface and not eligible_tacit:
        return []

    surface_text = "\n".join(
        f'- id: "{t.id}", fact: "{t.content}"' for t in unrevealed_surface
    ) or "(none remaining)"

    tacit_text = "\n".join(
        f'- id: "{t.id}", fact: "{t.content}"' for t in eligible_tacit
    ) or "(none remaining)"

    llm = ChatAnthropic(model="claude-sonnet-4-6", temperature=0.0)
    prompt = _RETRIEVAL_PROMPT.format(
        question=question,
        recent_context=recent_context or "(start of conversation)",
        surface_items=surface_text,
        tacit_items=tacit_text,
    )
    response = llm.invoke([LCHumanMessage(content=prompt)])

    try:
        raw = response.content.strip()
        # Strip markdown code fences if present.
        if "```" in raw:
            raw = re.sub(r"```[a-z]*\n?", "", raw).replace("```", "").strip()
        # Fallback: extract the JSON object from anywhere in the response.
        json_match = re.search(r"\{.*\}", raw, re.DOTALL)
        if json_match:
            raw = json_match.group(0)
        parsed = json.loads(raw)
        if not parsed.get("is_genuine", False):
            return []
        matched_ids = parsed.get("matched_ids", [])
    except (json.JSONDecodeError, AttributeError):
        matched_ids = []

    # Return items the LLM judged relevant. The prompt does the calibration work —
    # direct specificity, not topical association. The [:3] cap is a safety guardrail
    # for when the LLM misjudges despite good instructions. If the cap is consistently
    # binding, it means the prompt needs tuning, not the cap.
    all_unrevealed = {t.id: t for t in unrevealed_surface + unrevealed_tacit}
    return [all_unrevealed[id] for id in matched_ids if id in all_unrevealed][:3]
